---
- name: Install Yeoman
  npm: name=yo global=yes state=present
  when: npmInstalled|success
  register: yoInstalled
  tags: yeoman

- name: Install AngularJS generator
  npm: name=generator-angular global=yes state=present
  when: yoInstalled|success
  tags: yeoman

- name: Install AngularJS / Gulp generator
  npm: name=generator-gulp-angular global=yes state=present
  when: yoInstalled|success
  tags: yeoman

- name: Install HotTowel generator
  npm: name=generator-hottowel global=yes state=present
  when: yoInstalled|success and nodemonInstalled|success and gulpInstalled|success and bowerInstalled|success
  tags: yeoman
