---
- name: Install Yeoman
  npm: name=yo global=yes state=present
  when: nodeInstalled|success
  register: yoInstalled
  tags: yeoman

- name: Install AngularJS generator
  npm: name=generator-angular global=yes state=present
  when: yoInstalled|success
  tags: yeoman

- name: Install AngularJS / Gulp generator
  npm: name=generator-gulp-angular global=yes state=present
  when: yoInstalled|success
  tags: yeoman
