---
- name: Install Express
  npm: name=express global=yes state=present
  when: nodeInstalled|success
  register: expressInstalled
  tags: express
  
- name: Install Express generator
  npm: name=express-generator global=yes state=present
  when: expressInstalled|success
  tags: express
